version: "3.8"

services:
  app1:
    image: nginx:alpine
    container_name: app1-nginx
    ports:
      - "8081:80"

  app2:
    image: httpd:alpine
    container_name: app2-httpd
    ports:
      - "8082:80"
